# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nest_client.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11nest_client.proto\"\x0e\n\x01S\x12\t\n\x01s\x18\x01 \x01(\tb\x06proto3')



_S = DESCRIPTOR.message_types_by_name['S']
S = _reflection.GeneratedProtocolMessageType('S', (_message.Message,), {
  'DESCRIPTOR' : _S,
  '__module__' : 'nest_client_pb2'
  # @@protoc_insertion_point(class_scope:S)
  })
_sym_db.RegisterMessage(S)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _S._serialized_start=21
  _S._serialized_end=35
# @@protoc_insertion_point(module_scope)
