#!/bin/sh
DISK_SIZE=((SIZE))
DISK_LARGER_SIZE=

HOSTNAME=$(echo  $1 | base64 -d)
PROJNAME=$(echo $2 | base64 -d)

echo "using the hostname $HOSTNAME and project $PROJNAME"
mount -t proc /proc /proc
mount -t devtmpfs /dev /dev
mount -t sysfs /sys /sys
mount -t tmpfs /run /run
mount -t tmpfs -o exec /tmp /tmp
cp -rvf /etc /tmp/.
mount --bind /tmp/etc /etc
echo "nest ALL=(ALL:ALL) ALL" >> /etc/sudoers
mount -t tmpfs -o exec /home /home
adduser nest nest -D

echo "nest:pass" | chpasswd
mount -t 9p host9p /mnt
mount --bind /mnt /home/nest
ip link set eth0 up
udhcpc
mkdir /mnt/_internal
if [ ! -f /mnt/_internal/disk_debian_slim ]
then
    wget -O /mnt/_internal/disk_debian_slim "${HOSTNAME}"/disk.larger
fi
if [ ! -f /mnt/_internal/jdk.tar.gz ]
then
    wget -O /mnt/_internal/jdk.tar.gz "${HOSTNAME}"/jdk.tar.gz
    mkdir /mnt/_internal/jdk
    pv /mnt/_internal/jdk.tar.gz | gzip -d > /tmp/jdk.tar
    pv /tmp/jdk.tar | tar -C /mnt/_internal/jdk -xf -
    rm /tmp/jdk.tar
fi
mkdir /tmp/new-chroot
mount /mnt/_internal/disk_debian_slim /tmp/new-chroot
mount -t tmpfs /tmp/new-chroot/tmp /tmp/new-chroot/tmp
mkdir /tmp/new-chroot/tmp/rootfs
mount --bind / /tmp/new-chroot/tmp/rootfs
mkdir /tmp/new-chroot/tmp/jdk
cp -rvf /mnt/_internal/jdk /tmp/jdk

mount --bind /tmp/jdk /tmp/new-chroot/tmp/jdk
mkdir /dev/pts
mount -t devpts /dev/pts /dev/pts
mount --bind "/mnt/$PROJNAME" /home/nest
mkfifo -m 777 /tmp/srvStream
j17 java -cp / FakeMain & 2>&1 | sed 's/$/\r/'
/bin/nest-client &
while :
do
script -q -c "/bin/su nest -c\"cd /home/nest && exec sh\"" /dev/null
done